spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ok
  jackson:
    date-format: yyyy-MM-dd
    #time-zone: GMT+8

# GMT+8  %2B 转义 +   GMT%2B8 / UTC
# mysql8 驱动url后一定要加时区，否则报错


mybatis-plus:
  # config-location: classpath:mybatis-config.xml      # IllegalStateException: Property 'configuration' and 'configLocation' can not specified with together
  mapper-locations: classpath*:mapper/**/*Mapper.xml #  Maven 多模块项目的扫描路径需以 classpath*: 开头 （即加载多个 jar 包下的 XML 文件）
  type-aliases-package: com.imooc.mp.entity         #  Mapper.xml中就不用写实体类的全限定名
  configuration:
    map-underscore-to-camel-case: true             # mp默认值true  mybatis默认值 false
  global-config:
    db-config:
      field-strategy: default                        #  实体属性为null或空字符串 是否会插入
#      id-type: uuid    # mp id全局策略， 局部策略优于全局策略



logging:
  level:
    root: warn
    com.imooc.mp.mapper: trace   # trace 最低级别输出更多内容
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n'      # '%p%m%n' #p:级别 m:内容 n:换行